name: 'tekartik_material_asset'
version: 0.3.0
description: Material design assets
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
dev_dependencies:
  test: any
